[package]
name = "otus-program-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
borsh = { version = "1.5.1", features = ["derive"] }
solana-client = "2.0.7"
solana-sdk = "2.0.7"
uuid = { version = "1.10.0", features = ["v4"] }
